"""empty message

Revision ID: 961d3ea7ba31
Revises: 01f808f15b2e
Create Date: 2019-12-31 10:35:12.966741

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961d3ea7ba31'
down_revision = '01f808f15b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_until', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_until')
    # ### end Alembic commands ###
